export const GET_LIFEPOINTS = 'GET_LIFEPOINTS';
export const GET_LIFEPOINTS_SUCCESS = 'GET_LIFEPOINTS_SUCCESS';
export const GET_LIFEPOINTS_FAILURE = 'GET_LIFEPOINTS_FAILURE';

export const SAVE_LIFEPOINT = 'SAVE_LIFEPOINT';
export const SAVE_LIFEPOINT_SUCCESS = 'SAVE_LIFEPOINT_SUCCESS';
export const SAVE_LIFEPOINT_FAILURE = 'SAVE_LIFEPOINT_FAILURE';